### ISSUE TITLE
Run at startup

### ISSUE THREAD

**Issue by maman** [stayradiated/bar#1]
how do I run bar at startup/login?
i've tried to create user agents, and create automator app to run, but bar only display the “bar” itself, with no content..

**Comment by stayradiated** [comment]
I haven't actually gotten it to run  at startup yet. Currently I just open a terminal and start it manually.

I think the main problem is that the script that prints to the bar doesn't get executed properly, but I don't know why.

I'll have a look into it tomorrow.

**Comment by stayradiated** [comment]
I've got it working. Just had to make all the paths complete and absolute.
1. You will need to edit `app/js/config.js` and replace the `root` variable to match your setup.
2. Then you will need to edit `bin/init_bar_script.sh` and replace the `PRINTER` variable to match your setup. Possible `NODE` as well.
3. Then run `make` to put everything in a zip file called 'bar.nw'
4. You should be able to double-click `bar.nw` to open it directly in Node-Webkit.
5. This should start Bar and should also automatically run init_bar_script.sh and start printing the time.
6. If that all worked, then great! Add `bar.nw` to your login items (System Prefs > Users and Groups > Login Items) and it will should start on login.

If something didn't work for you, let me know and I'll see if I can sort it out.

**Comment by maman** [comment]
working great. thanks for the solution :+1:
