### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by jeffrey-ng** [stayradiated/bar#2]
Hi,

I seem to be having some problems with launching the bar.
Getting this error. Any help? Thanks. 
![screen shot 2014-02-23 at 12 16 10 pm](https://f.cloud.github.com/assets/1553313/2240810/5903a0a0-9cae-11e3-9fc7-2968c5ef611a.png)

**Comment by stayradiated** [comment]
Looks like it could be an incorrect file path.

Check that the following are set correctly:
- The `root` variable in `app/js/config.js` 
- The `PRINTER` variable in `bin/init_bar_script.sh`

**Comment by jeffrey-ng** [comment]
Wow... I missed the / at the end of the root variable. Sorry! Thanks for the help.
